.blink_env <- new.env(parent = emptyenv())

#' The mean-field model generator.
#'
#' By default returns the model that was compiled into the package at build time
#' (`src/malaria_ode.cpp`, generated by `odin2::odin_package()` from
#' `inst/odin/malaria_ode.R`), so a run never compiles anything at runtime.
#' Passing `odin_file` compiles an alternate odin source on the fly for
#' development, which requires the 'odin2' package (Suggests) and a C++ toolchain.
#' @param odin_file optional path to an odin source to compile instead.
#' @noRd
get_generator <- function(odin_file = NULL) {
  if (is.null(odin_file)) return(malaria_ode)     # compiled-in generator (R/dust.R)
  if (!requireNamespace("odin2", quietly = TRUE)) {
    stop("Compiling a custom `odin_file` needs the 'odin2' package.", call. = FALSE)
  }
  if (is.null(.blink_env$generators)) .blink_env$generators <- list()
  key <- normalizePath(odin_file, mustWork = TRUE)
  if (is.null(.blink_env$generators[[key]])) {
    .blink_env$generators[[key]] <- odin2::odin(odin_file, quiet = TRUE)
  }
  .blink_env$generators[[key]]
}

#' Run the mean-field (ODE) malaria model.
#'
#' @param timesteps number of days to simulate. Output has `timesteps + 1` rows
#'   (day 0 is the seeded equilibrium; days 1..timesteps are integrated).
#' @param parameters a malariasimulation::get_parameters() list (falciparum),
#'   optionally with interventions layered on via the `set_*` builders. The
#'   following are applied automatically from the list (no extra arguments):
#'   clinical treatment (time-varying), antimalarial resistance, bed nets, IRS,
#'   MDA/SMC/PMC, PEV (EPI + mass) and TBV vaccines, seasonality and flexible
#'   carrying capacity, and custom demography (`set_demography`: age-specific
#'   mortality and the resulting equilibrium age structure). P. vivax is rejected;
#'   the model is always compartmental (the individual-mosquito path does not
#'   apply). See the README for the mean-field approximations used by each module.
#'
#'   Two optional fields on the list tune how faithfully the mean field mirrors the
#'   IBM's per-individual arithmetic. Both default to the validated choice, so you
#'   normally leave them alone:
#'   \itemize{
#'     \item `bite_dedup` (default `1`) — reproduce the IBM's per-timestep bite
#'       deduplication. malariasimulation collects the day's bitten individuals in a
#'       bitset, so a person bitten repeatedly in one timestep is infected at most
#'       once: the daily infection probability is `(1 - exp(-EPS)) * b`, which
#'       saturates. Setting `0` uses the unbounded `b * EPS` instead, which
#'       over-predicts infection where exposure approaches one bite/person/day
#'       (seasonal peaks, high-`zeta` strata) but makes the `malariaEquilibrium`
#'       seed an exact fixed point — useful for equilibrium tests.
#'     \item `acquired_immunity_offset` (default `0`) — the IBM adds `+0.5` to
#'       positive acquired immunity inside the `b`/`phi`/`theta` Hill functions. That
#'       is a per-individual detail which does not carry over to a stratum mean; an
#'       A/B against the IBM ensemble mean favours `0`. Set `0.5` to reproduce the
#'       IBM's literal Hill calls.
#'   }
#' @param correlations accepted so the first three arguments mirror
#'   `malariasimulation::run_simulation(timesteps, parameters, correlations)`
#'   exactly (drop-in call compatibility). Intervention correlation is an
#'   individual-level feature with no mean-field analogue, so a non-NULL value is
#'   ignored with a warning (the ODE assumes independence between interventions).
#' @details Seasonal runs oscillate around a limit cycle rather than holding flat;
#'   the state is seeded at the annual-mean (aseasonal) equilibrium, so the first
#'   ~10 years are a transient onto the cycle and the seasonal annual-mean EIR
#'   sits a few percent below the aseasonal `init_EIR` target (nonlinear
#'   averaging). Use a burned-in cycle for calibration/comparison.
#' @param init_EIR target adult EIR (bites/adult/year). If NULL, taken from
#'   `parameters$init_EIR` (set by malariasimulation::set_equilibrium()).
#' @param age_lower age-group lower edges in **years** (default graded grid).
#' @param n_eir,n_foim,n_eip Erlang-chain stage counts for the EIR lag, FOIM lag
#'   and mosquito EIP. Larger values sharpen the (otherwise gamma-shaped) lags
#'   toward the IBM's fixed delays; equilibrium is exact for any value.
#' @param atol,rtol,step_size_max dust2 ODE-solver controls. The defaults
#'   (`1e-8`, `1e-8`, `1`) preserve the flat equilibrium exactly; for long dynamic
#'   projections a looser tolerance and larger step cap (e.g. `1e-6`, `1e-6`, `10`)
#'   run several times faster with negligible effect on aggregate outputs.
#' @param odin_file optional path to the odin source (development use).
#' @return a wide, malariasimulation-style daily count table, one row per output
#'   day. Columns:
#'   \itemize{
#'     \item `timestep` — output day (0..timesteps), the row key.
#'     \item per age band (tags in **days**, `<lo>_<hi>`): `n_age_*` (population),
#'       `n_detect_lm_*` and `p_detect_lm_*` (LM-positive count and PfPR
#'       proportion), `n_detect_pcr_*`, `n_inc_clinical_*`, `n_inc_severe_*` and
#'       `n_inc_*` (all-infection incidence) — all per-day counts.
#'     \item `ft` (treated fraction), `EIR` (per adult per year), `FOIM`.
#'     \item population-total infection-state counts `S_count`, `D_count`,
#'       `A_count`, `U_count`, `Tr_count`, `Ph_count` (diagnostic).
#'   }
#'   Incidence columns are per-day counts; do not thin rows before postie. Can be
#'   passed directly to postie::get_rates() / postie::get_prevalence().
#' @examples
#' \dontrun{
#' p <- malariasimulation::get_parameters()
#'
#' # daily wide count table, init_EIR supplied directly
#' out <- run_simulation_ode(timesteps = 3650, parameters = p, init_EIR = 20)
#' head(out[, c("timestep", "n_age_730_3650", "n_detect_lm_730_3650", "EIR")])
#'
#' # or let set_equilibrium() seed init_EIR into the parameter list
#' p2 <- malariasimulation::set_equilibrium(
#'   malariasimulation::get_parameters(), init_EIR = 5)
#' out2 <- run_simulation_ode(timesteps = 3650, parameters = p2)
#' }
#' @export
run_simulation_ode <- function(timesteps, parameters = NULL, correlations = NULL,
                               init_EIR = NULL,
                               age_lower = default_age_lower(),
                               n_eir = 10L, n_foim = 10L, n_eip = 20L,
                               atol = 1e-8, rtol = 1e-8, step_size_max = 1,
                               odin_file = NULL) {
  if (is.null(parameters)) {
    stop("`parameters` is required (a malariasimulation::get_parameters() list).")
  }
  if (!is.null(correlations)) {
    warning("`correlations` is accepted for run_simulation() signature ",
            "compatibility but not modelled: intervention correlation is an ",
            "individual-level feature with no mean-field analogue (the ODE ",
            "assumes independence). Ignoring it.", call. = FALSE)
  }
  if (is.null(init_EIR)) {
    init_EIR <- parameters$init_EIR
    if (is.null(init_EIR)) {
      stop("Provide `init_EIR` or run malariasimulation::set_equilibrium() first.")
    }
  }
  inp <- build_inputs(parameters, init_EIR, age_lower, n_eir, n_foim, n_eip,
                      timesteps = timesteps)
  generator <- get_generator(odin_file)
  # Robustness: the interpolate grids (pev/tbv "linear") are built to extend past
  # `timesteps` so the stepper never extrapolates them. step_size_max caps the step;
  # at the default 1 it binds only in the near-equilibrium regime (derivatives ~ 0,
  # where the adaptive stepper would otherwise propose a huge step past an interpolate
  # knot). For long dynamic projections a larger cap + looser atol/rtol trade a little
  # accuracy for speed; the equilibrium-preserving defaults (1, 1e-8) are unchanged.
  ctrl <- dust2::dust_ode_control(max_steps = max(1e5, 100 * timesteps),
                                  atol = atol, rtol = rtol, step_size_max = step_size_max)
  sys <- dust2::dust_system_create(generator, pars = inp$pars, n_particles = 1,
                                   ode_control = ctrl)
  dust2::dust_system_set_state_initial(sys)
  times <- seq(0, timesteps)
  events <- chemoprevention_events(inp$meta$parameters, timesteps)
  if (length(events) == 0) {
    y <- dust2::dust_system_simulate(sys, times)
  } else {
    y <- simulate_with_pulses(sys, times, events, inp$meta)
  }
  render_output(sys, y, times, inp)
}

#' Integrate with chemoprevention pulses applied between segments.
#' @noRd
simulate_with_pulses <- function(sys, times, events, meta) {
  uidx <- dust2::dust_unpack_index(sys)
  timesteps <- max(times)
  ev_days <- sort(unique(vapply(events, function(e) e$time, numeric(1))))
  ev_days <- ev_days[ev_days >= 1 & ev_days <= timesteps]
  bnds <- sort(unique(c(0, ev_days, timesteps)))
  cols <- vector("list", length(bnds) - 1)
  recorded_hi <- -1
  for (k in seq_len(length(bnds) - 1)) {
    lo <- bnds[k]; hi <- bnds[k + 1]
    seg_days <- times[times > recorded_hi & times <= hi]
    if (length(seg_days)) {
      cols[[k]] <- dust2::dust_system_simulate(sys, seg_days)
      recorded_hi <- max(seg_days)
    }
    if (hi %in% ev_days) {
      for (e in events[vapply(events, function(x) x$time == hi, logical(1))]) {
        apply_chemoprevention_pulse(sys, uidx, meta, e)
      }
    }
  }
  do.call(cbind, cols[!vapply(cols, is.null, logical(1))])
}

#' Default output age bands (days), taken from the parameter list's rendering
#' fields where present, always including 2-10y and all-ages.
#' @noRd
#' Age bands per output family, mirroring malariasimulation's rendering semantics.
#'
#' CRITICAL: each column family must be emitted ONLY over its own rendering list,
#' exactly as malariasimulation does (R/render.R: n_detect_* from
#' prevalence_rendering_*, n_inc_* from incidence_rendering_*, n_inc_clinical_*
#' from clinical_incidence_rendering_*, n_inc_severe_* from
#' severe_incidence_rendering_*, and only n_age_* over the union). Emitting every
#' family over the UNION produces OVERLAPPING strata — e.g. a 2-10y prevalence band
#' alongside a 0-5/5-15/15-100 clinical partition — and postie treats each
#' n_inc_clinical_* column as an independent age stratum. Any person-day-weighted
#' aggregate (postie::get_rates() |> weighted.mean(clinical, person_days)) then
#' double-counts the overlapped ages, inflating the all-age rate by
#' (1 + w*rho)/(1 + w) — measured at ~1.21 for clinical and ~1.10 for severe on a
#' site::site_parameters() list. Only fall back to the convenience 2-10y / all-age
#' bands when a family's own rendering list is empty (e.g. a bare get_parameters()).
#' @noRd
output_bands <- function(p, family = c("all", "prevalence", "incidence",
                                       "clinical", "severe")) {
  family <- match.arg(family)
  gather <- function(lo, hi) {
    lo <- p[[lo]]; hi <- p[[hi]]
    if (is.null(lo) || length(lo) == 0) return(NULL)
    Map(c, lo, hi)
  }
  default <- list(c(730, 3650), c(0, 36500))
  prev <- gather("prevalence_rendering_min_ages", "prevalence_rendering_max_ages")
  inc  <- gather("incidence_rendering_min_ages", "incidence_rendering_max_ages")
  clin <- gather("clinical_incidence_rendering_min_ages", "clinical_incidence_rendering_max_ages")
  sev  <- gather("severe_incidence_rendering_min_ages", "severe_incidence_rendering_max_ages")
  agrp <- gather("age_group_rendering_min_ages", "age_group_rendering_max_ages")
  or_default <- function(x) if (length(x)) x else default
  switch(family,
    prevalence = unique(or_default(prev)),
    incidence  = unique(or_default(inc)),
    clinical   = unique(or_default(clin)),
    severe     = unique(or_default(sev)),
    # n_age_* spans the union of everything (matching malariasimulation)
    all = unique(c(prev, inc, clin, sev, agrp, default)))
}

#' Render dust2 output into a wide malariasimulation-style count table that can
#' be passed directly to postie::get_rates() / postie::get_prevalence().
#' @noRd
render_output <- function(sys, y, times, inp) {
  st <- dust2::dust_unpack_state(sys, y)
  meta <- inp$meta
  hp <- meta$human_population
  age_mid <- meta$age_mid
  nt <- length(times)
  # per-age-group time series are [n_age, nt] matrices
  mat <- function(a) if (is.null(dim(a))) matrix(a, nrow = 1) else a
  n_g <- mat(st$n_g); det_lm_g <- mat(st$det_lm_g); det_pcr_g <- mat(st$det_pcr_g)
  clin_g <- mat(st$clin_g); sev_g <- mat(st$sev_g); inc_g <- mat(st$inc_g)

  band_sum <- function(m, lo, hi) {
    idx <- which(age_mid >= lo & age_mid < hi)
    if (length(idx) == 0) return(rep(0, ncol(m)))
    colSums(m[idx, , drop = FALSE])
  }

  out <- data.frame(timestep = times)
  p <- meta$parameters
  tag_of <- function(b) paste0(round(b[1]), "_", round(b[2]))
  # n_age_* over the union (as malariasimulation does): postie derives its
  # denominators by matching these to each incidence/detection column's tag.
  for (b in output_bands(p, "all")) {
    out[[paste0("n_age_", tag_of(b))]] <- band_sum(n_g, b[1], b[2]) * hp
  }
  # every other family strictly over ITS OWN rendering bands, so the strata each
  # postie column family sees form a partition (see output_bands()).
  for (b in output_bands(p, "prevalence")) {
    tag <- tag_of(b)
    n_age <- band_sum(n_g, b[1], b[2]) * hp
    n_lm  <- band_sum(det_lm_g, b[1], b[2]) * hp
    out[[paste0("n_detect_lm_", tag)]] <- n_lm
    out[[paste0("p_detect_lm_", tag)]] <- ifelse(n_age > 0, n_lm / n_age, 0)
    out[[paste0("n_detect_pcr_", tag)]] <- band_sum(det_pcr_g, b[1], b[2]) * hp
  }
  for (b in output_bands(p, "clinical")) {
    out[[paste0("n_inc_clinical_", tag_of(b))]] <- band_sum(clin_g, b[1], b[2]) * hp
  }
  for (b in output_bands(p, "severe")) {
    out[[paste0("n_inc_severe_", tag_of(b))]] <- band_sum(sev_g, b[1], b[2]) * hp
  }
  for (b in output_bands(p, "incidence")) {
    out[[paste0("n_inc_", tag_of(b))]] <- band_sum(inc_g, b[1], b[2]) * hp
  }
  out$ft <- as.numeric(st$ft_out)
  out$EIR <- as.numeric(st$EIR_yr)
  out$FOIM <- as.numeric(st$FOIM)
  # population-total infection-state fractions (diagnostic)
  out$S_count <- colSums(mat(st$S_g)) * hp
  out$D_count <- colSums(mat(st$D_g)) * hp
  out$A_count <- colSums(mat(st$A_g)) * hp
  out$U_count <- colSums(mat(st$U_g)) * hp
  out$Tr_count <- colSums(mat(st$Tr_g)) * hp
  out$Ph_count <- colSums(mat(st$Ph_g)) * hp
  out
}
