.fleet_env <- new.env(parent = emptyenv())

#' The mean-field model generator.
#'
#' By default returns the model that was compiled into the package at build time
#' (`src/malaria_daily.cpp`, generated by `odin2::odin_package()` from
#' `inst/odin/malaria_daily.R`), so a run never compiles anything at runtime.
#' Passing `odin_file` compiles an alternate odin source on the fly for
#' development, which requires the 'odin2' package (Suggests) and a C++ toolchain.
#' @param odin_file optional path to an odin source to compile instead.
#' @noRd
get_generator <- function(odin_file = NULL) {
  if (is.null(odin_file)) return(malaria_daily)   # compiled-in generator (R/dust.R)
  if (!requireNamespace("odin2", quietly = TRUE)) {
    stop("Compiling a custom `odin_file` needs the 'odin2' package.", call. = FALSE)
  }
  if (is.null(.fleet_env$generators)) .fleet_env$generators <- list()
  key <- normalizePath(odin_file, mustWork = TRUE)
  if (is.null(.fleet_env$generators[[key]])) {
    .fleet_env$generators[[key]] <- odin2::odin(odin_file, quiet = TRUE)
  }
  .fleet_env$generators[[key]]
}

#' Run the mean-field malaria model.
#'
#' The population is advanced one day at a time, in the order malariasimulation
#' resolves a day: immunity decay, biting and infection, one competing draw per
#' person between infection and progression, a day of the mosquito model, and
#' deaths replaced by births. See `vignette("model")`.
#'
#' @param timesteps number of days to simulate. Output has one row per day,
#'   `1..timesteps`, as malariasimulation's does: row `t` holds the state at the
#'   start of day `t` and the incidence during it, so row 1 is the seed.
#' @param parameters a malariasimulation::get_parameters() list, optionally
#'   with interventions layered on via the `set_*` builders. The following are
#'   applied automatically from the list (no extra arguments): clinical
#'   treatment (time-varying), antimalarial resistance, bed nets, IRS,
#'   MDA/SMC/PMC, PEV (EPI + mass) and TBV vaccines, seasonality and flexible
#'   carrying capacity, and custom demography (`set_demography`: age-specific
#'   mortality and the resulting equilibrium age structure). The parasite is
#'   `parameters$parasite`, as in malariasimulation: a list from
#'   `get_parameters(parasite = "vivax")` runs the P. vivax model --
#'   hypnozoite batches and relapse, radical cure with liver-stage protection
#'   (`CQ_PQ_params_vivax`, `CQ_TQ_params_vivax`), no severe disease. MDA, SMC
#'   and PMC are refused under vivax because malariasimulation itself fails on
#'   them. The model is always compartmental (the individual-mosquito path does
#'   not apply). `vignette("using")` indexes the mean-field approximations and
#'   when each one matters.
#'
#'   **The target EIR is read from this list**, as `parameters$init_EIR`, which is
#'   where `malariasimulation` puts it and reads it from too. Seed it the same way
#'   you would for the IBM, before calling this function:
#'   `parameters <- malariasimulation::set_equilibrium(parameters, init_EIR = 20)`.
#'   That call also stores `eq_params`, which `fleet` honours if present. Setting
#'   `parameters$init_EIR` by hand works but skips that.
#'
#'   **Call `set_equilibrium()` last.** It freezes all 56 equilibrium parameters,
#'   51 of them translated from the IBM list, at the values they held when it ran,
#'   and `fleet` merges that stored set over the live list. So an edit made
#'   *after* it -- another `set_*()` builder, or `parameters$du <- 10` by hand --
#'   is a silent no-op for
#'   anything in that set, and the run is bit-identical to one without the edit.
#'   The IBM reads those fields directly and would honour the edit, so this is a
#'   real difference between the two models rather than a detail of this one.
#'   `fleet` warns when a live value disagrees with the stored one. If a
#'   calibration loop varies any of them, re-call `set_equilibrium()` each
#'   iteration.
#'
#'   Three further optional fields tune how faithfully the mean field mirrors the
#'   IBM. The first two are per-individual arithmetic, the third is a seeding
#'   convention; all three default to the validated choice, so you normally leave
#'   them alone:
#'   \itemize{
#'     \item `bite_dedup` (default `1`): reproduce the IBM's per-timestep bite
#'       deduplication. malariasimulation collects the day's bitten individuals in a
#'       bitset, so a person bitten repeatedly in one timestep is infected at most
#'       once: the daily infection probability is `(1 - exp(-EPS)) * b`, which
#'       saturates. Setting `0` lets every bite infect independently instead,
#'       `1 - exp(-b * EPS)`, which over-predicts infection where exposure
#'       approaches one bite/person/day (seasonal peaks, high-`zeta` strata).
#'       Neither makes the `malariaEquilibrium` seed an exact fixed point:
#'       `vignette("model")` lists the departures from that solution in its
#'       initial-conditions section. Leave it at `1` for any scientific run.
#'     \item `acquired_immunity_offset` (default `0` for P. falciparum, `0.5` for
#'       P. vivax): the IBM adds `+0.5` to positive acquired immunity inside the
#'       `b`/`phi`/`theta` Hill functions. That is a per-individual detail. The
#'       falciparum model reads its curves at a stratum mean, where it does not
#'       carry over and an A/B against the IBM ensemble mean favours `0`; the vivax
#'       model reads them at quadrature nodes that stand for individuals (see
#'       `immunity_spread`), where it does, so it takes the IBM's `0.5`.
#'     \item `immunity_spread` (default `TRUE`; P. vivax only): model the spread
#'       of immunity among people who share an age, heterogeneity group and
#'       hypnozoite batch count. In the IBM they differ by their batch *history*,
#'       and the vivax immunity curves are steep enough that the mean probability
#'       of clinical disease can be several times the probability at the mean
#'       immunity. fleet carries each cell's second moment of immunity and averages
#'       the curves over a gamma with that mean and variance. `FALSE` evaluates
#'       them at the cell mean, which under-predicts clinical incidence in
#'       school-age children and young adults by up to 40% once the IBM has built
#'       up its spread.
#'     \item `hold_init_EIR` (default `FALSE`): only matters with `set_demography()`.
#'       malariasimulation's `set_equilibrium()` sizes the mosquito population from
#'       the equilibrium under its *default* exponential age structure, so under a
#'       custom demography the IBM drifts to whatever transmission that density
#'       supports. By default fleet replicates that: it takes the IBM's mosquito
#'       density and seeds at the EIR its own equilibrium under the custom age
#'       structure then supports, which is generally *not* `init_EIR`. Set `TRUE`
#'       to seed at `init_EIR` exactly instead. Either way the seed is the
#'       `malariaEquilibrium` solution at that EIR, and it relaxes slightly, as
#'       every seed does.
#'   }
#' @param correlations accepted so the first three arguments mirror
#'   `malariasimulation::run_simulation(timesteps, parameters, correlations)`
#'   exactly (drop-in call compatibility). Intervention correlation is an
#'   individual-level feature with no mean-field analogue, so a non-NULL value is
#'   ignored with a warning (the model assumes independence between interventions).
#'   `tuning` is the *fourth* argument: an [ode_tuning()] object (or a list of its
#'   fields) passed positionally here would land in `correlations` and be thrown
#'   away, so that is an error rather than a silently defaulted run.
#' @details The seed is where malariasimulation's own seed is: the
#'   `malariaEquilibrium` solution for `init_EIR`, the humans under the treatment
#'   coverage in force at timestep 0 and the mosquitoes sized under the coverage
#'   at timestep 1, as `set_equilibrium()` and the IBM's initialisation do. It is
#'   close to the daily model's fixed point but not on it: prevalence relaxes by
#'   under half a per cent, incidence by a few per cent over the first years,
#'   more at high transmission. Seasonal runs oscillate around a limit cycle
#'   rather than holding flat; the state is seeded at the annual-mean (aseasonal)
#'   equilibrium, so the first ~10 years are a transient onto the cycle and the
#'   seasonal annual-mean EIR sits about 7% below the aseasonal `init_EIR`
#'   target (nonlinear averaging). Use a burned-in window for calibration and
#'   comparison.
#' @param tuning discretisation settings, from [ode_tuning()]. A plain named
#'   list of the fields you want to change is also accepted; every field left out
#'   keeps its default. These are numerical-approximation knobs, not model
#'   parameters: nothing epidemiological lives here.
#' @param ... not used. Named arguments that were top-level before the signature
#'   was cut back to `malariasimulation::run_simulation()`'s are caught here and
#'   reported with the call that replaces them.
#' @return a wide daily table in malariasimulation's layout, one row per day. The
#'   columns follow malariasimulation's rendering rules: a parameter list gives the
#'   columns the IBM would give it, under the same names and with the same
#'   meanings, as far as a mean field carries them. Columns:
#'   \itemize{
#'     \item `timestep`: output day (1..timesteps), the row key.
#'     \item age-banded counts, one set per band in the parameter list's rendering
#'       lists and none for an empty list: `n_detect_lm_*`, `p_detect_lm_*` (not
#'       for vivax) and `n_detect_pcr_*` over `prevalence_rendering_*`; `n_inc_*` and `p_inc_*`
#'       over `incidence_rendering_*`; `n_inc_clinical_*` and `p_inc_clinical_*`
#'       over `clinical_incidence_rendering_*`; `n_inc_severe_*` and
#'       `p_inc_severe_*` over `severe_incidence_rendering_*`; and `n_age_*`
#'       (population) over all of those and `age_group_rendering_*` together. The
#'       tag is `<lower>_<upper>` in days, formatted as malariasimulation formats
#'       it. A band `[lower, upper]` holds the whole-day ages `lower` to `upper`,
#'       both included, as in the IBM, so `0_1824` and `1825_5474` partition the
#'       age axis while `0_1825` and `1825_5475` share one day's cohort.
#'
#'       In the IBM an `n_*` column is a sampled count and its `p_*` partner the
#'       expected count behind it: `p_detect_lm_*` is the clinically detected
#'       count plus each asymptomatic person's probability of detection, a count
#'       and not a prevalence. A mean field carries expectations, so here the two
#'       are the same number. The exception is `p_inc_*`, which is 0 because
#'       malariasimulation 3.0.0 renders it from `incidence_min_ages`, a field no
#'       parameter list sets, and so returns 0 for it too. Prevalence is
#'       `n_detect_lm_*` / `n_age_*`, as postie computes it.
#'
#'       A band is aggregated by exact overlap with the model's age groups, so it
#'       need not align with the `age_lower` grid. The one group that is not a
#'       finite interval is the absorbing top group, which holds everyone from its
#'       lower edge upward: a band is given all of it if it reaches above that edge
#'       and none of it otherwise. A band ending inside it (60-85 years on the
#'       default grid, whose top group starts at 80) is therefore given all of it,
#'       and a band ending exactly on its lower edge none of it, which warns, as
#'       does a band that selects no age group at all.
#'     \item `n_infections` (new infections at all ages) and, when clinical
#'       treatment is deployed, `ft` (the fraction of clinical cases treated), as
#'       in the IBM.
#'     \item P. vivax: `n_relapses` (the day's relapse infections) and
#'       `n_with_hypnozoites` (people carrying at least one batch), and by age
#'       `n_inc_relapse_*` over `incidence_relapse_rendering_*` and
#'       `n_with_hypnozoites_*`, with the band's population as `n_*`, over
#'       `n_with_hypnozoites_rendering_*`. A vivax `A` is LM-detectable by
#'       definition, so `n_detect_lm_*` counts all of it, and the IBM renders no
#'       `p_detect_lm_*` for vivax; a severe band on a vivax list renders, as
#'       the IBM's does, as 0.
#'     \item population totals by infection state, `S_count`, `A_count`,
#'       `D_count`, `U_count` and `Tr_count`, counted as the IBM counts them:
#'       someone a drug is protecting is uninfected, and so in `S_count`.
#'     \item the immunity means over the population: `ica_mean`, `icm_mean`,
#'       `ib_mean`, `iva_mean`, `ivm_mean` and `id_mean` for falciparum,
#'       `ica_mean`, `icm_mean`, `iaa_mean`, `iam_mean` and `hypnozoites_mean`
#'       (the mean batch count) for vivax; and each by age, `<name>_mean_*` with
#'       the band's population as `n_*`, over its `<name>_rendering_*`. The IBM
#'       seeds falciparum's maternal immunity from the equilibrium bin 0.1 years
#'       older than each person, so for the first months its `icm_mean` and
#'       `ivm_mean` sit below `fleet`'s, whose births take their mothers'.
#'     \item three columns malariasimulation does not have: `EIR` (infectious
#'       bites per adult per year), `FOIM` (the force of infection on the first
#'       mosquito species) and `Ph_count` (how many of `S_count` a drug is
#'       protecting).
#'   }
#'   malariasimulation columns this table does not carry: `n_bitten`,
#'   `infectivity`, `EIR_<species>`, `FOIM_<species>`, `mu_<species>`, the
#'   mosquito compartment counts and `total_M_<species>`, `natural_deaths`, and
#'   the treatment and intervention tallies (`n_treated`, `n_smc_treated` and
#'   the rest). The IBM renders `n_inc_relapse_*` only on days with a relapse in
#'   the band, and NA otherwise; a mean field's expected count is never zero.
#'
#'   Incidence columns are per-day counts; do not thin rows before postie. The
#'   table can be passed directly to postie::get_rates() / postie::get_prevalence().
#' @seealso [ode_tuning()] for the discretisation settings.
#' @examples
#' \dontrun{
#' # exactly the call you would make to malariasimulation::run_simulation()
#' p <- malariasimulation::set_equilibrium(
#'   malariasimulation::get_parameters(), init_EIR = 20)
#' out <- run_simulation_ode(timesteps = 3650, parameters = p)
#' head(out[, c("timestep", "n_age_730_3650", "n_detect_lm_730_3650", "EIR")])
#'
#' # the same run on an age grid twice as fine
#' fine <- run_simulation_ode(3650, p,
#'   tuning = list(age_lower = default_age_lower(n_group = 105)))
#' }
#' @export
run_simulation_ode <- function(timesteps, parameters = NULL, correlations = NULL,
                               tuning = ode_tuning(), ...) {
  .reject_moved_args(...)
  if (is.null(parameters)) {
    stop("`parameters` is required (a malariasimulation::get_parameters() list).")
  }
  .reject_tuning_as_correlations(correlations)
  if (!is.null(correlations)) {
    warning("`correlations` is accepted for run_simulation() signature ",
            "compatibility but not modelled: intervention correlation is an ",
            "individual-level feature with no mean-field analogue (the model ",
            "assumes independence). Ignoring it.", call. = FALSE)
  }
  tn <- as_ode_tuning(tuning)
  ## `timesteps` is validated here, next to the init_EIR guard, because nothing
  ## downstream fails on it usefully: a fractional value was silently truncated by
  ## seq(), and every other bad value surfaced as an error from deep inside seq(),
  ## dust2 or the interpolation grids that never named the argument at fault
  ## ("wrong sign in 'by' argument", "'to' must be a finite number", "Time variable
  ## 'cc_times' must be strictly increasing"). The swapped-argument call
  ## run_simulation_ode(parameters, timesteps) lands here too, and used to die on
  ## `parameters$init_EIR` with "$ operator is invalid for atomic vectors".
  if (!is.numeric(timesteps) || length(timesteps) != 1L || !is.finite(timesteps) ||
      timesteps < 1 || timesteps != round(timesteps)) {
    stop("`timesteps` must be a single finite whole number >= 1 (the number of ",
         "days to simulate; the run returns one row per day, 1..timesteps). Got ",
         .describe_value(timesteps), ".\n",
         "  run_simulation_ode(timesteps = 3650, parameters = p)", call. = FALSE)
  }
  init_EIR <- parameters$init_EIR
  if (is.null(init_EIR)) {
    stop("`parameters$init_EIR` is not set, so there is no target transmission ",
         "to seed at. Seed the list the way you would for the IBM:\n",
         "  parameters <- malariasimulation::set_equilibrium(parameters, init_EIR = 20)\n",
         "  run_simulation_ode(timesteps, parameters)", call. = FALSE)
  }
  inp <- build_inputs(parameters, init_EIR, tn$age_lower, n_ph = tn$n_ph,
                      n_phc = tn$n_phc, n_sub = tn$n_sub, timesteps = timesteps)
  generator <- get_generator(tn$odin_file)
  sys <- dust2::dust_system_create(generator, pars = inp$pars, n_particles = 1, dt = 1)
  dust2::dust_system_set_state_initial(sys)
  # The update from time t - 1 to t is the IBM's timestep t, and it records that
  # day's counts, so times 1..timesteps are malariasimulation's rows 1..timesteps.
  times <- seq_len(timesteps)
  # Record only the per-age outputs and scalars render_output() reads, not the
  # full state: with the prophylaxis chains and delay lines the state is several
  # times the size of the outputs, and the full daily trajectory of a 30-year run
  # would otherwise cost hundreds of MB.
  uidx <- dust2::dust_unpack_index(sys)
  out_idx <- unlist(uidx[OUTPUT_VARS], use.names = FALSE)
  events <- chemoprevention_events(inp$meta$parameters, timesteps)
  if (length(events) == 0) {
    y <- dust2::dust_system_simulate(sys, times, index_state = out_idx)
  } else {
    y <- simulate_with_pulses(sys, times, events, inp$meta, uidx, out_idx)
  }
  render_output(y, times, inp, uidx, out_idx)
}

#' Describe a bad argument compactly, for an error message.
#' @noRd
.describe_value <- function(x) {
  if (is.numeric(x) && length(x) == 1L) return(format(x))
  if (is.atomic(x) && length(x) == 1L && !is.null(x)) return(deparse(x, nlines = 1L))
  paste0("a ", class(x)[1], " of length ", length(x))
}

## The third positional argument is `correlations`, mirroring
## malariasimulation::run_simulation(timesteps, parameters, correlations). `tuning`
## is the FOURTH, so run_simulation_ode(t, p, ode_tuning(...)) put the tuning into
## `correlations`, which is ignored -- the run silently used default tuning while
## the warning it printed talked about intervention correlation. Caught by name and
## reported with the call that works, in the voice of .reject_moved_args().
#' @noRd
.reject_tuning_as_correlations <- function(correlations) {
  if (is.null(correlations)) return(invisible(NULL))
  known <- c(setdiff(names(formals(ode_tuning)), "..."), RETIRED_TUNING)
  if (inherits(correlations, "fleet_ode_tuning")) {
    stop("an `ode_tuning()` object was passed as the third argument, which is ",
         "`correlations` -- the signature mirrors ",
         "malariasimulation::run_simulation(timesteps, parameters, correlations), ",
         "so `tuning` is the fourth. Pass it by name:\n",
         "  run_simulation_ode(timesteps, parameters, tuning = ode_tuning(...))",
         call. = FALSE)
  }
  nm <- names(correlations)
  if (is.list(correlations) && length(correlations) && !is.null(nm) &&
      all(nzchar(nm)) && all(nm %in% known)) {
    stop("the third argument is `correlations`, but this list holds only `tuning` ",
         "field(s) (", paste0("`", nm, "`", collapse = ", "), ") -- the signature ",
         "mirrors malariasimulation::run_simulation(timesteps, parameters, ",
         "correlations), so `tuning` is the fourth. Pass it by name:\n",
         "  run_simulation_ode(timesteps, parameters, tuning = list(",
         paste0(nm, " = ...", collapse = ", "), "))", call. = FALSE)
  }
  invisible(NULL)
}

# odin output/aggregate variables recorded from each run (all of render_output's inputs)
OUTPUT_VARS <- c("n_g", "det_lm_g", "det_pcr_g", "clin_g", "sev_g", "inc_g",
                 "relapse_g", "hyp_g",
                 "S_g", "D_g", "A_g", "U_g", "Tr_g", "Ph_g", "EIR_yr", "FOIM", "ft_out",
                 "ica_g", "icm_g", "ib_g", "iva_g", "ivm_g", "id_g",
                 "iaa_g", "iam_g", "hypk_g")

## The immunities malariasimulation renders means of, per parasite
## (processes.R imm_var_names), with the output each is summed in.
IMMUNITY_VARS <- list(
  falciparum = c(ica = "ica_g", icm = "icm_g", ib = "ib_g", iva = "iva_g",
                 ivm = "ivm_g", id = "id_g"),
  vivax = c(ica = "ica_g", icm = "icm_g", iaa = "iaa_g", iam = "iam_g",
            hypnozoites = "hypk_g"))

#' Simulate with chemoprevention pulses applied between segments.
#'
#' A round scheduled for timestep `t` is applied to the state after day `t` has
#' been simulated, so it acts from day `t + 1`: the IBM delivers it as an event,
#' which fires after the day's processes, and its updates land at the end of the
#' day.
#' @noRd
simulate_with_pulses <- function(sys, times, events, meta, uidx, out_idx) {
  timesteps <- max(times)
  ev_days <- sort(unique(vapply(events, function(e) e$time, numeric(1))))
  # A round scheduled before day 1 cannot be delivered: the run simulates days
  # 1..timesteps from the seed. malariasimulation schedules these events at
  # `<timestep> - 1` days from the start of its loop (initialise_events()) and
  # individual rejects the resulting negative delay outright --
  # set_mda/set_smc(timesteps = 0, ...) dies with "delay must be >= 0", so a
  # timestep-0 round is not a round the IBM ever runs. fleet keeps running and
  # drops it, but says so: silently returning a trajectory identical to no
  # chemoprevention at all is what this warning exists to stop.
  early <- ev_days[ev_days < 1]
  if (length(early)) {
    warning("chemoprevention round(s) scheduled at timestep ",
            paste(early, collapse = ", "), " cannot be delivered and are dropped: ",
            "the simulation runs days 1..", timesteps, " from the seed. ",
            "malariasimulation rejects such a schedule outright ",
            "(\"delay must be >= 0\"). Schedule the round at timestep 1 or later.",
            call. = FALSE)
  }
  ev_days <- ev_days[ev_days >= 1 & ev_days <= timesteps]
  bnds <- sort(unique(c(0, ev_days, timesteps)))
  cols <- vector("list", length(bnds) - 1)
  recorded_hi <- -1
  for (k in seq_len(length(bnds) - 1)) {
    lo <- bnds[k]; hi <- bnds[k + 1]
    seg_days <- times[times > recorded_hi & times <= hi]
    if (length(seg_days)) {
      cols[[k]] <- dust2::dust_system_simulate(sys, seg_days, index_state = out_idx)
      recorded_hi <- max(seg_days)
    }
    if (hi %in% ev_days) {
      for (e in events[vapply(events, function(x) x$time == hi, logical(1))]) {
        apply_chemoprevention_pulse(sys, uidx, meta, e)
      }
    }
  }
  do.call(cbind, cols[!vapply(cols, is.null, logical(1))])
}

#' Age bands per output family, as malariasimulation renders them.
#'
#' Each column family is emitted over its own rendering list and nothing else, as
#' malariasimulation does (R/render.R, R/human_infection.R): the detection columns
#' over prevalence_rendering_*, n_inc_* / p_inc_* over incidence_rendering_*, the
#' clinical pair over clinical_incidence_rendering_*, the severe pair over
#' severe_incidence_rendering_*, and n_age_* over the union of those four lists and
#' age_group_rendering_*, deduplicated and sorted by lower then upper edge, as
#' create_age_group_renderer() sorts them. An empty list renders nothing, so a bare
#' get_parameters() gives the 2-10 prevalence columns and no incidence columns, in
#' the IBM and here alike.
#'
#' Emitting a family over the UNION instead would produce OVERLAPPING strata (a
#' 2-10 prevalence band alongside a 0-5/5-15/15-100 clinical partition), and postie
#' treats each n_inc_clinical_* column as an independent age stratum: any
#' person-day-weighted aggregate (postie::get_rates() |> weighted.mean(clinical,
#' person_days)) then double-counts the overlapped ages, by ~1.21x on all-age
#' clinical and ~1.10x on severe incidence for a site::site_parameters() list.
#' @noRd
output_bands <- function(p, family = c("all", "prevalence", "incidence",
                                       "clinical", "severe", "relapse", "n_hypnozoites",
                                       "ica", "icm", "ib", "iva", "ivm", "id", "iaa",
                                       "iam", "hypnozoites")) {
  family <- match.arg(family)
  gather <- function(stem) {
    lo <- p[[paste0(stem, "_min_ages")]]; hi <- p[[paste0(stem, "_max_ages")]]
    if (!length(lo)) return(list())
    Map(c, lo, hi)
  }
  prev <- gather("prevalence_rendering")
  inc  <- gather("incidence_rendering")
  clin <- gather("clinical_incidence_rendering")
  sev  <- gather("severe_incidence_rendering")
  if (family != "all") {
    # the vivax families and the immunity means render over their own lists and
    # stay out of the n_age_* union, as in the IBM
    return(unique(switch(family, prevalence = prev, incidence = inc,
                         clinical = clin, severe = sev,
                         relapse = gather("incidence_relapse_rendering"),
                         n_hypnozoites = gather("n_with_hypnozoites_rendering"),
                         gather(paste0(family, "_rendering")))))
  }
  u <- unique(c(prev, inc, clin, sev, gather("age_group_rendering")))
  if (!length(u)) return(u)
  u[order(vapply(u, `[`, numeric(1), 1), vapply(u, `[`, numeric(1), 2))]
}

#' A rendering band's span on fleet's age axis.
#'
#' malariasimulation renders a band `[lower, upper]` over whole-day ages with both
#' ends included -- in_age_range() selects `birth` in `[t - upper, t - lower]` --
#' and nobody is under a day old when a day is rendered, because births land at the
#' end of a day. fleet's age axis starts at 0 at birth, so at the start of day `t`,
#' the state a row reports, a person the IBM would call `a` days old sits at
#' `x = a - 1`. The band is therefore `x` in `[max(1, ceiling(lower)) - 1,
#' floor(upper))`: `[0, 1824]` and `[1825, 5474]` tile the axis, `[0, 1825]` and
#' `[1825, 5475]` share one day's cohort as they do in the IBM, and `[0, 0]` is
#' empty.
#' @return `c(lo, hi)`, a half-open interval in days (empty when `hi <= lo`).
#' @noRd
ibm_band_span <- function(lower, upper) {
  lo <- max(1, ceiling(lower)) - 1
  c(lo, max(lo, floor(upper)))
}

#' Warn when a band stops exactly on the absorbing top group's lower edge.
#'
#' The top age group is open-ended: it holds everyone from its lower edge upward,
#' and a band is given all of it if it reaches above that edge and none of it if it
#' stops on it. The second is the easy slip. An all-age band `[0, 36500]` on a grid
#' built with `max_age = 100` asks for ages below 36500 days and so leaves out the
#' whole group, 1.3% of the population at the default demography, where the IBM's
#' `[0, 36500]` holds everyone. A band that stops short of the edge is taken to
#' mean it, and does not warn.
#' @param spans list of `c(lo, hi)` spans on fleet's age axis, named by tag.
#' @param n_g `[n_age, nt]` population per age group per output day.
#' @noRd
warn_top_group_edge <- function(spans, n_g, age_lo) {
  top <- age_lo[length(age_lo)]
  hit <- vapply(spans, function(s) s[1] < top && abs(s[2] - top) <= 1e-9 * max(1, top),
                logical(1))
  if (!any(hit)) return(invisible(NULL))
  total <- colSums(n_g)
  share <- mean(n_g[length(age_lo), total > 0] / total[total > 0])
  warning("rendering band(s) ", paste0("`", names(spans)[hit], "`", collapse = ", "),
          " stop exactly at ", format(round(top)), " days, the lower edge of the ",
          "absorbing top age group, and so render none of it: ",
          format(100 * share, digits = 3), "% of the population is missing from ",
          "them, and from every rate postie derives from them. Give the band an ",
          "upper edge above ", format(round(top)), " days, or move the grid's top ",
          "edge with tuning = ode_tuning(age_lower = default_age_lower(max_age = ...)).",
          call. = FALSE)
  invisible(share)
}

#' Render dust2 output into malariasimulation's daily table, which can be passed
#' directly to postie::get_rates() / postie::get_prevalence().
#'
#' Column names, meanings and conditions follow malariasimulation's renderers (see
#' output_bands() and ibm_band_span()); tests/testthat/test-output-parity.R runs
#' the IBM beside this and checks it column by column.
#' @noRd
render_output <- function(y, times, inp, uidx, out_idx) {
  # y holds only the rows out_idx (in that order); pull each variable's rows back
  # out by position, as an [n, nt] matrix (per-age series) or a length-nt vector
  get <- function(nm, as_matrix = TRUE) {
    m <- y[match(uidx[[nm]], out_idx), , drop = FALSE]
    if (as_matrix) m else as.numeric(m)
  }
  meta <- inp$meta
  hp <- meta$human_population
  p <- meta$parameters
  # per-age-group time series are [n_age, nt] matrices
  n_g <- get("n_g"); det_lm_g <- get("det_lm_g"); det_pcr_g <- get("det_pcr_g")
  clin_g <- get("clin_g"); sev_g <- get("sev_g"); inc_g <- get("inc_g")

  ## Exact-overlap band weighting. A model age group contributes to a band the
  ## fraction of its OWN width that lies inside the band's span on fleet's age axis
  ## (ibm_band_span()) -- the weighting apply_chemoprevention_pulse() uses for
  ## chemoprevention targeting (R/interventions.R). It replaces midpoint membership
  ## ("the group is in the band iff its midpoint is"), which had two failure modes:
  ##   * a band narrower than the group it lands in captures NO midpoint, and the
  ##     whole column family came back as hard zeros -- 52 of the 65 single-year
  ##     bands from 15 to 80 years on the default grid.
  ##   * a partial overlap counted the whole group or none of it, so e.g. the
  ##     standard 6-59-month band came back 2.2% light on a default parameter list,
  ##     and that error flowed into every PfPR denominator and postie person-day.
  ## Over a set of spans that tile part of the age axis these weights sum to exactly
  ## 1 per age group inside it (a group straddling a boundary is SPLIT between the
  ## two bands), so no family double-counts and no family loses anyone it renders.
  age_lo <- meta$age_lo; age_hi <- meta$age_hi
  wid <- age_hi - age_lo
  band_weights <- function(lo, hi) {
    num <- pmax(0, pmin(hi, age_hi) - pmax(lo, age_lo))
    # The absorbing top group is open-ended (width Inf), so its upper edge is not a
    # real boundary and num/wid means nothing there: it is captured iff the span
    # reaches ABOVE its lower edge, and then wholly, since everyone in it is older.
    #
    # `hi > age_lo`, not `hi >= age_lo`, and deliberately so. A span [lo, hi) whose
    # hi lands exactly on the top group's lower edge asks for ages strictly below
    # that edge, and every person in the top group is at or above it -- so it gets
    # none of them, and the grid's own top edge is the only place that answer can
    # surprise anyone (it is where `age_lower`'s top edge and a rendering band's top
    # edge collide, e.g. the all-age band [0, 36500] on a grid built with
    # max_age = 100). Relaxing this to `>=` would hand the top group to that band AND
    # to any band starting at the same edge, so both would claim it -- exactly the
    # double-counting the tiling property above exists to prevent (measured at +21%
    # on all-age clinical incidence when postie last saw overlapping strata). A rule
    # that cannot double-count and a warning that names the missing people
    # (warn_top_group_edge()) beats a rule that silently reassigns them.
    ifelse(is.finite(wid), num / wid, as.numeric(lo <= age_lo & hi > age_lo))
  }
  ## A band's tag is malariasimulation's own, paste0(lower, "_", upper) on the raw
  ## values: 182.5 stays 182.5, and 1e5 becomes "1e+05", which make.names() below
  ## turns into the "1e.05" the IBM's data.frame() gives it.
  tag_of <- function(b) paste0(b[1], "_", b[2])
  ## Weights are computed once per distinct band (each is asked for by up to two
  ## families), which also makes the empty-band warning fire exactly once.
  wt_cache <- list()
  band_wt <- function(b) {
    key <- tag_of(b)
    if (!is.null(wt_cache[[key]])) return(wt_cache[[key]])
    sp <- ibm_band_span(b[1], b[2])
    wt <- band_weights(sp[1], sp[2])
    if (sum(wt) == 0) {
      warning("rendering age band [", b[1], ", ", b[2], "] days selects no model ",
              "age group, so every `*_", key, "` column is 0. ",
              if (sp[2] <= sp[1]) {
                paste0("It holds no whole-day age of at least one day, and nobody ",
                       "is younger than that when malariasimulation renders a day.")
              } else {
                paste0("The age grid covers [", age_lo[1], ", ", age_lo[length(age_lo)],
                       ") days plus an open-ended top group from ",
                       age_lo[length(age_lo)], " days, which only a band reaching ",
                       "its lower edge can render. Widen the band, or extend the grid ",
                       "with tuning = ode_tuning(age_lower = default_age_lower(max_age = ...)).")
              }, call. = FALSE)
    }
    wt_cache[[key]] <<- wt
    wt
  }
  band_sum <- function(m, b) colSums(m * band_wt(b)) * hp

  ## Columns in the order malariasimulation first renders them: the infection and
  ## treatment tallies, the incidence families, the transmission scalars, the
  ## vivax relapse and hypnozoite families, the state counts, the detection
  ## family, and n_age_* last.
  vivax <- identical(meta$parasite, "vivax")
  out <- data.frame(timestep = times)
  out$n_infections <- colSums(inc_g) * hp
  # the IBM renders ft only when some clinical treatment coverage is non-zero
  # (populate_incidence_rendering_columns())
  if (sum(unlist(p$clinical_treatment_coverages)) > 0) out$ft <- get("ft_out", FALSE)
  # relapse infections, which the IBM renders for every vivax run (default 0)
  if (vivax) out$n_relapses <- colSums(get("relapse_g")) * hp
  ## Each incidence family is a count and, beside it, malariasimulation's p_*
  ## column: the sum of each person's probability of the event, the expectation
  ## the sampled count scatters around. A mean field carries expectations, so the
  ## two are the same number here. p_inc_* is the exception: malariasimulation
  ## 3.0.0 renders it from incidence_min_ages (R/human_infection.R), a field no
  ## parameter list sets, so the column only ever holds its default of 0 there,
  ## and it is 0 here to match.
  for (b in output_bands(p, "incidence")) {
    out[[paste0("n_inc_", tag_of(b))]] <- band_sum(inc_g, b)
    out[[paste0("p_inc_", tag_of(b))]] <- 0
  }
  for (b in output_bands(p, "clinical")) {
    out[[paste0("n_inc_clinical_", tag_of(b))]] <- band_sum(clin_g, b)
    out[[paste0("p_inc_clinical_", tag_of(b))]] <- out[[paste0("n_inc_clinical_", tag_of(b))]]
  }
  for (b in output_bands(p, "severe")) {
    out[[paste0("n_inc_severe_", tag_of(b))]] <- band_sum(sev_g, b)
    out[[paste0("p_inc_severe_", tag_of(b))]] <- out[[paste0("n_inc_severe_", tag_of(b))]]
  }
  out$EIR <- get("EIR_yr", FALSE)
  out$FOIM <- get("FOIM", FALSE)
  ## P. vivax: relapses by age over incidence_relapse_rendering_*, the number of
  ## people carrying at least one hypnozoite batch, and that number by age over
  ## n_with_hypnozoites_rendering_* with the band's population beside it as
  ## n_<lower>_<upper>, as create_n_with_hypnozoites_age_renderer_process()
  ## renders it. The IBM renders n_inc_relapse_* only on days with a relapse in
  ## the band, NA otherwise; a mean field's expected count is never zero.
  if (vivax) {
    relapse_g <- get("relapse_g"); hyp_g <- get("hyp_g")
    for (b in output_bands(p, "relapse")) {
      out[[paste0("n_inc_relapse_", tag_of(b))]] <- band_sum(relapse_g, b)
    }
    out$n_with_hypnozoites <- colSums(hyp_g) * hp
    for (b in output_bands(p, "n_hypnozoites")) {
      out[[paste0("n_", tag_of(b))]] <- band_sum(n_g, b)
      out[[paste0("n_with_hypnozoites_", tag_of(b))]] <- band_sum(hyp_g, b)
    }
  }
  ## Population totals by state, as the IBM counts them. A drug-protected person is
  ## an uninfected person in state S there (prophylaxis is a timer, not a state),
  ## so the prophylaxis chains are part of S_count; Ph_count says how much of it.
  ph <- colSums(get("Ph_g")) * hp
  out$S_count <- colSums(get("S_g")) * hp + ph
  out$A_count <- colSums(get("A_g")) * hp
  out$D_count <- colSums(get("D_g")) * hp
  out$U_count <- colSums(get("U_g")) * hp
  out$Tr_count <- colSums(get("Tr_g")) * hp
  out$Ph_count <- ph
  ## Immunity means over the whole population, as create_variable_mean_renderer_
  ## process() renders them: the falciparum six or the vivax five (with
  ## hypnozoites, the mean batch count), each the population's total over its
  ## size. A mean field's is the mean of the cell means, weighted by who is in
  ## each cell.
  imm <- IMMUNITY_VARS[[if (vivax) "vivax" else "falciparum"]]
  n_tot <- colSums(n_g)
  for (v in names(imm)) out[[paste0(v, "_mean")]] <- colSums(get(imm[[v]])) / n_tot
  ## Detection. The IBM's n_detect_lm_* samples each asymptomatic person's
  ## detection and p_detect_lm_* sums the probabilities instead: both are counts,
  ## and a mean field's expected count is both. Prevalence is n_detect_lm_* over
  ## n_age_*, as postie computes it. A vivax A is LM-detectable by definition, so
  ## there is nothing to sum and the IBM renders no p_detect_lm_* for vivax.
  for (b in output_bands(p, "prevalence")) {
    lm <- band_sum(det_lm_g, b)
    out[[paste0("n_detect_lm_", tag_of(b))]] <- lm
    if (!vivax) out[[paste0("p_detect_lm_", tag_of(b))]] <- lm
    out[[paste0("n_detect_pcr_", tag_of(b))]] <- band_sum(det_pcr_g, b)
  }
  # n_age_* over the union, sorted as the IBM sorts it: postie derives every
  # denominator by matching these to each incidence/detection column's tag.
  union <- output_bands(p, "all")
  for (b in union) out[[paste0("n_age_", tag_of(b))]] <- band_sum(n_g, b)
  ## ...and the immunity means by age, over each immunity's own
  ## <name>_rendering_* list, each with its band's population as n_<lower>_<upper>
  ## (create_age_variable_mean_renderer_process()).
  for (v in names(imm)) {
    for (b in output_bands(p, v)) {
      out[[paste0("n_", tag_of(b))]] <- band_sum(n_g, b)
      out[[paste0(v, "_mean_", tag_of(b))]] <- band_sum(get(imm[[v]]), b) / band_sum(n_g, b)
    }
  }
  spans <- lapply(union, function(b) ibm_band_span(b[1], b[2]))
  names(spans) <- vapply(union, tag_of, character(1))
  warn_top_group_edge(spans, n_g, age_lo)
  # what malariasimulation's data.frame() does to the same names
  names(out) <- make.names(names(out), unique = TRUE)
  out
}
